export const ROLES = {
  ADMIN: "admin",
  MANAGER: "manager",
  SALES: "sales",
  MARKETING: "marketing",
  SUPPORT: "support",
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const RESOURCES = {
  DASHBOARD: "dashboard",
  CONTACTS: "contacts",
  COMPANIES: "companies",
  DEALS: "deals",
  ACTIVITIES: "activities",
  PRODUCTS: "products",
  QUOTES: "quotes",
  USERS: "users",
  EMAIL_TEMPLATES: "email_templates",
  IMPORT_EXPORT: "import_export",
  BULK_ACTIONS: "bulk_actions",
  PERMISSIONS: "permissions",
  REPORTS: "reports",
} as const;

export type Resource = typeof RESOURCES[keyof typeof RESOURCES];

export const ACTIONS = {
  VIEW: "view",
  CREATE: "create",
  EDIT: "edit",
  DELETE: "delete",
  EXPORT: "export",
  IMPORT: "import",
} as const;

export type Action = typeof ACTIONS[keyof typeof ACTIONS];

export interface PermissionRule {
  resource: Resource;
  action: Action;
  enabled: boolean;
}

export const DEFAULT_PERMISSIONS: Record<Role, PermissionRule[]> = {
  [ROLES.ADMIN]: [
    { resource: RESOURCES.DASHBOARD, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.USERS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.USERS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.USERS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.USERS, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.REPORTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.REPORTS, action: ACTIONS.EXPORT, enabled: true },
  ],
  [ROLES.MANAGER]: [
    { resource: RESOURCES.DASHBOARD, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.USERS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.REPORTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.REPORTS, action: ACTIONS.EXPORT, enabled: true },
  ],
  [ROLES.SALES]: [
    { resource: RESOURCES.DASHBOARD, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.IMPORT, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.IMPORT, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.IMPORT, enabled: false },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.REPORTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.REPORTS, action: ACTIONS.EXPORT, enabled: true },
  ],
  [ROLES.MARKETING]: [
    { resource: RESOURCES.DASHBOARD, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.DELETE, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.IMPORT, enabled: true },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.EXPORT, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.REPORTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.REPORTS, action: ACTIONS.EXPORT, enabled: true },
  ],
  [ROLES.SUPPORT]: [
    { resource: RESOURCES.DASHBOARD, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.EXPORT, enabled: false },
    { resource: RESOURCES.CONTACTS, action: ACTIONS.IMPORT, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.EXPORT, enabled: false },
    { resource: RESOURCES.COMPANIES, action: ACTIONS.IMPORT, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.DEALS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.DEALS, action: ACTIONS.EXPORT, enabled: false },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.CREATE, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.EDIT, enabled: true },
    { resource: RESOURCES.ACTIVITIES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.PRODUCTS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.QUOTES, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.QUOTES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.USERS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.VIEW, enabled: true },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.CREATE, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.EMAIL_TEMPLATES, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.IMPORT, enabled: false },
    { resource: RESOURCES.IMPORT_EXPORT, action: ACTIONS.EXPORT, enabled: false },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.BULK_ACTIONS, action: ACTIONS.DELETE, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.PERMISSIONS, action: ACTIONS.EDIT, enabled: false },
    { resource: RESOURCES.REPORTS, action: ACTIONS.VIEW, enabled: false },
    { resource: RESOURCES.REPORTS, action: ACTIONS.EXPORT, enabled: false },
  ],
};

export function getResourceLabel(resource: Resource): string {
  return resource.split('_').map(word => 
    word.charAt(0).toUpperCase() + word.slice(1)
  ).join(' ');
}

export function getActionLabel(action: Action): string {
  return action.charAt(0).toUpperCase() + action.slice(1);
}

export function getRoleLabel(role: Role): string {
  return role.charAt(0).toUpperCase() + role.slice(1);
}
